source 'https://github.com/cocoapods/Specs.git'
#source ''
platform:ios, '8.0'
use_frameworks!
targetsArray = ['THYG']
targetsArray.each do |t|
	target t do
	pod 'AFNetworking'
#    pod 'MWPhotoBrowser'
	pod 'Bugly'
	pod 'DZNEmptyDataSet'
	pod 'IQKeyboardManager'
	pod 'Masonry'
	pod 'MJRefresh'
	pod 'MSWeakTimer'
    pod 'ReactiveCocoa','~> 2.5’
	pod 'SDCycleScrollView'
	pod 'SVProgressHUD'
    pod 'HDAlertView'
    pod 'WechatOpenSDK'
#    pod 'YZDisplayViewController'
    pod 'YYKit'
    pod 'FDKeychain'
    pod 'Realm'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'FDFullscreenPopGesture'
#    pod 'SDWebImage', '3.7'
    pod 'WMPageController'
    pod 'UMCCommonLog'
    pod 'UMCCommon'
#    pod 'UMCSecurityPlugins'
    #    pod 'UMCShare'
#    pod 'UMCShare/UI'
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
#    pod 'AliPaySDK'
	end
end
