source 'https://github.com/cocoapods/Specs.git'
platform:ios, '8.0'
use_frameworks!
targetsArray = ['THYG']
targetsArray.each do |t|
	target t do
	pod 'AFNetworking'
	pod 'Bugly'
	pod 'DZNEmptyDataSet'
	pod 'IQKeyboardManager'
	pod 'Masonry'
	pod 'MJExtension'
	pod 'MJRefresh'
	pod 'MSWeakTimer'
	pod 'ReactiveCocoa','~> 2.5’
	pod 'RTRootNavigationController'
	pod 'SDCycleScrollView'
	pod 'SVProgressHUD'
	pod 'UMCCommon'
#    pod 'UMCShare'
    pod 'UMCShare/UI'
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'HDAlertView'
    pod 'WechatOpenSDK'
    pod 'YZDisplayViewController'
    pod 'YYKit'
    pod 'FDKeychain'
#    pod 'AliPaySDK'
	end
end
