source 'https://github.com/cocoapods/Specs.git'
platform:ios, '8.0'
use_frameworks!
targetsArray = ['THYG','THYG_PRO']
targetsArray.each do |t|
	target t do
	pod 'AFNetworking'
	pod 'Bugly'
	pod 'DZNEmptyDataSet'
	pod 'IQKeyboardManager'
	pod 'Masonry'
	pod 'MJRefresh'
#    pod 'ReactiveCocoa','~> 2.5’
	pod 'SDCycleScrollView'
	pod 'SVProgressHUD'
    pod 'WechatOpenSDK'
    pod 'YYKit'
    pod 'FMDB'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'FDFullscreenPopGesture'
    pod 'WMPageController'
    pod 'MBProgressHUD'
    pod 'UMCCommonLog'
    pod 'UMCCommon'
#    pod 'UMCShare/UI'
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'HXPhotoPicker'
	end
end
